title: The Welcoming Committee
author: theWelcomingCommittee
email: mari.dietrich@protonmail.ch
description: > # this means to ignore newlines until "baseurl:"
this is a temporary bunch of stuff before we get into the nitty gritty of art stuff. 

# social links

github_username:  theWelcomingCommittee # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
